### ISSUE TITLE
Crash with Charm Beekeeper [Villager Fix 2.0.2+1.16.5]

### ISSUE THREAD

**Issue by TestSerber** [DrexHD/VillagerConfig#20]
`Description: Ticking entity

java.nio.file.InvalidPathException: Illegal char <:> at index 5: Charm:beekeeper.json
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
	at java.nio.file.Path.resolve(Path.java:515)
	at me.drex.villagerfix.villager.TradeOfferParser.<init>(TradeOfferParser.java:35)
	at me.drex.villagerfix.villager.TradeOfferParser.of(TradeOfferParser.java:71)
	at me.drex.villagerfix.villager.TradeOfferParser.of(TradeOfferParser.java:64)
	at net.minecraft.entity.passive.VillagerEntity.redirect$bmp000$putCustomRecipes(VillagerEntity:1643)
	at net.minecraft.entity.passive.VillagerEntity.fillRecipes(VillagerEntity:879)
	at net.minecraft.entity.passive.MerchantEntity.getOffers(MerchantEntity:115)
	at net.minecraft.entity.passive.VillagerEntity.method_21723(VillagerEntity:448)
	at net.minecraft.entity.passive.VillagerEntity.clearDailyRestockCount(VillagerEntity:1029)
	at net.minecraft.entity.passive.VillagerEntity.shouldRestock(VillagerEntity:438)
	at net.minecraft.entity.ai.brain.task.VillagerWorkTask.run(VillagerWorkTask:58)
	at net.minecraft.entity.ai.brain.task.VillagerWorkTask.run(VillagerWorkTask:18)
	at net.minecraft.entity.ai.brain.task.Task.tryStarting(Task:49)
	at net.minecraft.class_4103$class_4216$1.method_19561(class_4103.java:96)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at net.minecraft.class_4103$class_4216$1.run(class_4103.java:97)
	at net.minecraft.entity.ai.brain.task.CompositeTask.run(CompositeTask:53)
	at net.minecraft.entity.ai.brain.task.Task.tryStarting(Task:49)
	at net.minecraft.entity.ai.brain.Brain.startTasks(Brain:506)
	at net.minecraft.entity.ai.brain.Brain.tick(Brain:465)
	at net.minecraft.entity.passive.VillagerEntity.mobTick(VillagerEntity:272)
	at net.minecraft.entity.mob.MobEntity.tickNewAi(MobEntity:744)
	at net.minecraft.entity.LivingEntity.tickMovement(LivingEntity:2508)
	at net.minecraft.entity.mob.MobEntity.tickMovement(MobEntity:542)
	at net.minecraft.entity.passive.PassiveEntity.tickMovement(PassiveEntity:127)
	at net.minecraft.entity.LivingEntity.tick(LivingEntity:2254)
	at net.minecraft.entity.mob.MobEntity.tick(MobEntity:342)
	at net.minecraft.entity.passive.VillagerEntity.tick(VillagerEntity:313)
	at net.minecraft.server.world.ServerWorld.tickEntity(ServerWorld:621)
	at net.minecraft.world.World.tickEntity(World:561)
	at net.minecraft.server.world.ServerWorld.tick(ServerWorld:411)
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:871)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer:811)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer:91)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:257)
	at java.lang.Thread.run(Thread.java:832)`

This is all the info I can provide.

**Comment by DrexHD** [comment]
Fixed in Version 3.0.0
